// src/catalogos.ts
export type OpcionCat = { value: string; label: string };

export const CAT: Record<string, OpcionCat[]> = {
  tipo_id: [
    { value: 'RC', label: 'RC – Registro Civil' },
    { value: 'TI', label: 'TI – Tarjeta de Identidad' },
    { value: 'CC', label: 'CC – Cédula de Ciudadanía' },
    { value: 'CE', label: 'CE – Cédula de Extranjería' },
    { value: 'PA', label: 'PA – Pasaporte' },
    { value: 'MS', label: 'MS – Menor sin Identificación' },
    { value: 'AS', label: 'AS – Adulto sin Identificación' },
    { value: 'CD', label: 'CD – Carnet Diplomático' },
    { value: 'SD', label: 'SD – Salvoconducto' },
    { value: 'PE', label: 'PE – Permiso Especial' },
  ],
  sexo: [
    { value: 'M', label: 'M – Masculino' },
    { value: 'F', label: 'F – Femenino' },
  ],
  regimen: [
    { value: 'C', label: 'C – Contributivo' },
    { value: 'S', label: 'S – Subsidiado' },
    { value: 'P', label: 'P – Excepción' },
    { value: 'E', label: 'E – Especial' },
    { value: 'N', label: 'N – No asegurado' },
  ],
  pertenencia_etnica: [
    { value: '1', label: '1 – Indígena' },
    { value: '2', label: '2 – ROM (gitano)' },
    { value: '3', label: '3 – Raizal San Andrés' },
    { value: '4', label: '4 – Palenquero' },
    { value: '5', label: '5 – Negro/Afro/Mulato' },
    { value: '6', label: '6 – Ninguna de las anteriores' },
    { value: '55', label: '55 – Ente territorial' },
  ],
  tipo_estudio: [
    { value: '5', label: '5 – Inmunohistoquímica' },
    { value: '6', label: '6 – Citometría de flujo' },
    { value: '7', label: '7 – Clínica exclusivamente' },
    { value: '8', label: '8 – Otro' },
    { value: '9', label: '9 – Genética' },
    { value: '10', label: '10 – Patología básica' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '99', label: '99 – Desconocido' },
  ],
  motivo_sin_histo: [
    { value: '1', label: '1 – Coagulopatía' },
    { value: '2', label: '2 – Localización del tumor' },
    { value: '3', label: '3 – Estado funcional del usuario' },
    { value: '4', label: '4 – Negativa del usuario/acudiente' },
    { value: '5', label: '5 – Administrativa' },
    { value: '6', label: '6 – Imágenes o laboratorios' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – Tiene histopatología' },
    { value: '99', label: '99 – Desconocido' },
  ],
  histologia: [
    { value: '1', label: '1 – Adenocarcinoma' },
    { value: '2', label: '2 – Carcinoma escamocelular' },
    { value: '3', label: '3 – Carcinoma basocelular' },
    { value: '4', label: '4 – Carcinoma NOS' },
    { value: '5', label: '5 – Oligodendroglioma' },
    { value: '6', label: '6 – Astrocitoma' },
    { value: '7', label: '7 – Ependimoma' },
    { value: '8', label: '8 – Neuroblastoma' },
    { value: '9', label: '9 – Meduloblastoma' },
    { value: '10', label: '10 – Hepatoblastoma' },
    { value: '11', label: '11 – Rabdomiosarcoma' },
    { value: '12', label: '12 – Leiomiosarcoma' },
    { value: '13', label: '13 – Osteosarcoma' },
    { value: '17', label: '17 – Otros sarcomas' },
    { value: '20', label: '20 – Otros tipos histológicos' },
    { value: '23', label: '23 – Melanoma' },
    { value: '24', label: '24 – Carcinoma papilar de tiroides' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – Sin histopatología' },
    { value: '99', label: '99 – Desconocido' },
  ],
  grado_diferenciacion: [
    { value: '1', label: '1 – Bien diferenciado (G1)' },
    { value: '2', label: '2 – Moderadamente diferenciado (G2)' },
    { value: '3', label: '3 – Mal diferenciado (G3)' },
    { value: '4', label: '4 – Anaplásico/Indiferenciado (G4)' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '94', label: '94 – Sólido sin grado en patología' },
    { value: '95', label: '95 – No es sólido (hematolinfático)' },
    { value: '98', label: '98 – Sin histopatología' },
    { value: '99', label: '99 – Desconocido' },
  ],
  her2_realizado: [
    { value: '1', label: '1 – Sí se realizó' },
    { value: '2', label: '2 – No se realizó' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '97', label: '97 – No aplica (cáncer mama in situ)' },
    { value: '98', label: '98 – No aplica (no es cáncer de mama)' },
    { value: '99', label: '99 – Desconocido' },
  ],
  resultado_her2: [
    { value: '1', label: '1 – +++ (positivo)' },
    { value: '2', label: '2 – ++ (equívoco)' },
    { value: '3', label: '3 – + (negativo)' },
    { value: '4', label: '4 – 0 ó – (negativo)' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '97', label: '97 – No aplica (in situ)' },
    { value: '98', label: '98 – No aplica (no es mama)' },
    { value: '99', label: '99 – Desconocido' },
  ],
  dukes: [
    { value: '1', label: '1 – Dukes A' },
    { value: '2', label: '2 – Dukes B' },
    { value: '3', label: '3 – Dukes C' },
    { value: '4', label: '4 – Dukes D' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica (no es colorrectal)' },
    { value: '99', label: '99 – Desconocido' },
  ],
  ann_arbor: [
    { value: '1', label: '1 – Estadio I' }, { value: '2', label: '2 – Estadio II' },
    { value: '3', label: '3 – Estadio III' }, { value: '4', label: '4 – Estadio IV' },
    { value: '5', label: '5 – Estadio IA' }, { value: '6', label: '6 – Estadio IB' },
    { value: '7', label: '7 – Estadio IIA' }, { value: '8', label: '8 – Estadio IIB' },
    { value: '9', label: '9 – Estadio IIIA' }, { value: '10', label: '10 – Estadio IIIB' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica' },
    { value: '99', label: '99 – Desconocido' },
  ],
  gleason: [
    { value: '11', label: '11 – Gleason ≤ 6 (3+3)' },
    { value: '12', label: '12 – Gleason 7 (3+4)' },
    { value: '13', label: '13 – Gleason 7 (4+3)' },
    { value: '14', label: '14 – Gleason 8 (4+4/3+5/5+3)' },
    { value: '15', label: '15 – Gleason 9-10' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '97', label: '97 – Próstata, diagnóstico clínico' },
    { value: '98', label: '98 – No aplica (no es próstata)' },
    { value: '99', label: '99 – Desconocido' },
  ],
  objetivo: [
    { value: '1', label: '1 – Curación' },
    { value: '2', label: '2 – Paliación exclusivamente' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '99', label: '99 – Desconocido' },
  ],
  objetivo_periodo: [
    { value: '1', label: '1 – Observación pretratamiento' },
    { value: '2', label: '2 – Tratamiento curativo/paliativo' },
    { value: '3', label: '3 – Seguimiento oncológico' },
    { value: '4', label: '4 – 1 y 2' },
    { value: '5', label: '5 – 2 y 3' },
    { value: '6', label: '6 – 1, 2 y 3' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '99', label: '99 – Sin intervención en el periodo' },
  ],
  si_no: [
    { value: '1', label: '1 – Sí' },
    { value: '2', label: '2 – No' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '99', label: '99 – Desconocido' },
  ],
  recibio_qt: [
    { value: '1', label: '1 – Sí recibió terapia sistémica' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica (no fue propuesta)' },
  ],
  ubicacion_esquema: [
    { value: '1', label: '1 – Neoadyuvancia' },
    { value: '2', label: '2 – Tratamiento inicial curativo sin cirugía' },
    { value: '3', label: '3 – Adyuvancia' },
    { value: '11', label: '11 – Manejo de recaída' },
    { value: '12', label: '12 – Manejo de enf. metastásica' },
    { value: '13', label: '13 – Manejo paliativo' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '97', label: '97 – Solo un esquema (último = primero)' },
    { value: '98', label: '98 – No aplica' },
  ],
  caracteristicas_esq: [
    { value: '1', label: '1 – Finalizado, esquema completo' },
    { value: '2', label: '2 – Finalizado, esquema incompleto' },
    { value: '3', label: '3 – No finalizado, aún bajo tratamiento' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica' },
  ],
  motivo_fin_esq: [
    { value: '1', label: '1 – Toxicidad de medicamentos' },
    { value: '2', label: '2 – Otros motivos médicos' },
    { value: '3', label: '3 – Muerte' },
    { value: '4', label: '4 – Cambio de EPS' },
    { value: '5', label: '5 – Abandono de terapia' },
    { value: '6', label: '6 – No disponibilidad de medicamentos' },
    { value: '7', label: '7 – Otros motivos administrativos' },
    { value: '8', label: '8 – Otras causas' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica' },
  ],
  recibio_cirugia: [
    { value: '1', label: '1 – Sí fue sometido a cirugía' },
    { value: '2', label: '2 – No recibió cirugía' },
    { value: '55', label: '55 – Ente territorial' },
  ],
  recibio_rt: [
    { value: '1', label: '1 – Sí recibió radioterapia' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica (no fue propuesta)' },
  ],
  recibio_trasplante: [
    { value: '1', label: '1 – Sí recibió trasplante CPH' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica' },
  ],
  tipo_tratamiento_corte: [
    { value: '1', label: '1 – Radioterapia' },
    { value: '2', label: '2 – Terapia sistémica' },
    { value: '3', label: '3 – Cirugía' },
    { value: '4', label: '4 – 1 y 2' }, { value: '5', label: '5 – 1 y 3' },
    { value: '6', label: '6 – 2 y 3' }, { value: '7', label: '7 – Manejo expectante' },
    { value: '8', label: '8 – En seguimiento post-tratamiento' },
    { value: '9', label: '9 – Antecedente de cáncer' },
    { value: '10', label: '10 – 1, 2 y 3' },
    { value: '11', label: '11 – Cuidado paliativo/terapia complementaria' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica (fallecido/abandonó)' },
  ],
  resultado_oncologico: [
    { value: '1', label: '1 – Pseudoprogresión (inmunoterapia)' },
    { value: '2', label: '2 – Progresión o recaída' },
    { value: '3', label: '3 – Respuesta parcial' },
    { value: '4', label: '4 – Respuesta completa' },
    { value: '5', label: '5 – Enfermedad estable' },
    { value: '6', label: '6 – Abandono/alta voluntaria' },
    { value: '7', label: '7 – En seguimiento por antecedente' },
    { value: '8', label: '8 – Pendiente iniciar tratamiento' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '97', label: '97 – Aún bajo tratamiento inicial' },
    { value: '98', label: '98 – Aún bajo tratamiento de recaída' },
    { value: '99', label: '99 – Fallecido o desafiliado' },
  ],
  estado_vital: [
    { value: '1', label: '1 – Vivo' },
    { value: '2', label: '2 – Fallecido' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '99', label: '99 – Desconocido' },
  ],
  causa_muerte: [
    { value: '1', label: '1 – Muerte asociada al cáncer' },
    { value: '2', label: '2 – Patología clínica no relacionada' },
    { value: '3', label: '3 – Causa externa' },
    { value: '4', label: '4 – Causa no conocida' },
    { value: '55', label: '55 – Ente territorial' },
    { value: '98', label: '98 – No aplica (usuario vivo)' },
  ],
  novedad_administrativa: [
    { value: '0', label: '0 – Sin novedad' },
    { value: '1', label: '1 – Ingresó con diagnóstico previo' },
    { value: '2', label: '2 – Nuevo diagnóstico en este período' },
    { value: '3', label: '3 – Diagnóstico antiguo no reportado' },
    { value: '4', label: '4 – Falleció' },
    { value: '5', label: '5 – Desafiliado' },
    { value: '6', label: '6 – Eliminar (corrección auditoría)' },
    { value: '7', label: '7 – Alta voluntaria' },
    { value: '8', label: '8 – Cambio de tipo/número de ID' },
    { value: '9', label: '9 – Abandono (imposible ubicar)' },
    { value: '10', label: '10 – No incluido anterior + fallecido' },
    { value: '11', label: '11 – Trasladado de IPS' },
    { value: '12', label: '12 – Dos o más cánceres en este período' },
    { value: '13', label: '13 – No incluido anterior + desafiliado' },
    { value: '14', label: '14 – Ente territorial' },
    { value: '15', label: '15 – Comunidad migrante Venezuela' },
    { value: '16', label: '16 – Cambio de CIE-10' },
  ],
  novedad_clinica: [
    { value: '1', label: '1 – Manejo inicial curativo' },
    { value: '3', label: '3 – Finalizó tratamiento, en seguimiento' },
    { value: '8', label: '8 – Abandono de tratamiento' },
    { value: '9', label: '9 – Alta voluntaria' },
    { value: '10', label: '10 – Manejo expectante' },
    { value: '11', label: '11 – Manejo paliativo' },
    { value: '12', label: '12 – Fallecido o desafiliado' },
    { value: '55', label: '55 – Ente territorial' },
  ],

  clasificacion_riesgo: [
    { value: '1',  label: '1 – Estándar, bajo o favorable' },
    { value: '2',  label: '2 – Bajo intermedio' },
    { value: '3',  label: '3 – Intermedio' },
    { value: '4',  label: '4 – Alto intermedio' },
    { value: '5',  label: '5 – Alto o desfavorable' },
    { value: '6',  label: '6 – Favorable temprano' },
    { value: '7',  label: '7 – Desfavorable temprano' },
    { value: '8',  label: '8 – Favorable avanzado' },
    { value: '9',  label: '9 – Desfavorable avanzado' },
    { value: '10', label: '10 – R1' },
    { value: '11', label: '11 – R2' },
    { value: '12', label: '12 – R3' },
    { value: '13', label: '13 – R4' },
    { value: '97', label: '97 – Otro no definido' },
    { value: '98', label: '98 – No Aplica' },
    { value: '99', label: '99 – Desconocido' },
  ],
};